services:
  postgres-db:
    image: postgres:16
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: reports
    ports:
      - 5434:5432
    volumes:
      - ./postgres-db/postgres_data:/var/lib/postgresql/data
